name: hungerGames
main: me.helmetk.hungerGames.hungerGames
version: 0.1

commands:
  hungergames:
    description: Comando de prueba
    permission: hungerGames.hungergames
    usage: /hungergames start
