name: hungerGames
main: me.helmetk.hungerGames.hungerGames
version: 0.1

commands:
  hungergames:
    description: Play the Hunger Games!
    permission: hungerGames.hungergames
    usage: User /hungergames help to the Help page.
