name: hungerGames
main: me.helmetk.hungerGames.hungerGames
version: 0.1

commands:
  hungergames:
    description: Comando para iniciar/detener los HungerGames
    permission: hungerGames.hungergames
    usage: /hungergames start/stop
